#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 22 18:15:29 2018

@author: deep
"""

def biggest(aDict):
    '''
    aDict: A dictionary, where all the values are lists.

    returns: The key with the largest number of values associated with it
    '''
    # Your Code Here
    values = list(aDict.values())
    if not values:
        return None
    count = [len(l) for l in values]
    index = count.index(max(count))
    for key in aDict:
        if aDict[key] == values[index]:
            break
    return key       

    
    
