#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 21 10:59:17 2018

@author: deep
"""

def gcdIter(a, b):
    '''
    a, b: positive integers
    
    returns: a positive integer, the greatest common divisor of a & b.
    '''
    # Your code here
    if a < b:
        testvalue = a
    elif a == b:
        return a
    else:
        testvalue = b
        
    while (testvalue > 0):
        if a % testvalue == 0:
            if b % testvalue == 0:
                return testvalue
        testvalue -= 1
        
gcdIter(9, 12)        
        
        
