#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 21 21:21:55 2018

@author: deep
"""

def oddTuples(aTup):
    '''
    aTup: a tuple
    
    returns: tuple, every other element of aTup. 
    '''
    # Your Code Here
    result = ()
    for index, t in enumerate(aTup):
        if index % 2 == 0:
            result = result + (t,)
    return result        
        
