#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 14 15:50:57 2018

@author: deep
"""

# Paste your code into this box
print("Please think of a number between 0 and 100!")

low = 0
high = 100


while True:
    guess = (low + high) // 2
    print("Is your secret number {}?".format(guess))
    ans = input("Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly.")
    if ans == 'l':
        low = guess
    elif ans == 'h':
        high = guess
    elif ans == 'c':
        print("secret number is", guess)
        break
    else:
        print("Sorry, I did not understand your input.")
    
    
    