#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
A program to print the longest subsequence of string containing letters in alphabetical order
Created on Fri Feb  9 10:50:30 2018

@author: deep
"""

s = input("input a string")
temp_str = s[0]
final_str = ""

for i in range(len(s) - 1):
    if ord(s[i]) - 97 > ord(s[i + 1]) - 97:
        # append the character in temp string and put final string = temp string
        if final_str != "":
            if len(temp_str) > len(final_str):
                final_str = temp_str
        else:
            final_str = temp_str
        temp_str = s[i + 1]    
    else:
        temp_str = temp_str + s[i + 1]
else:
    if final_str != "":
        if len(temp_str) > len(final_str):
            final_str = temp_str
    else:
        final_str = temp_str        
print(final_str)        
        
        








    

        
        
        
    

